# Generated by Django 5.2.11 on 2026-06-19 22:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0001_initial'),
        ('contributions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerStatementLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Gerado em')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP')),
                ('purpose', models.CharField(blank=True, help_text='e.g., demande de pension, contrôle interne', max_length=200, verbose_name='Finalidade')),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='career_statement_logs', to='affiliates.affiliate', verbose_name='Afiliado')),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='career_statements_generated', to=settings.AUTH_USER_MODEL, verbose_name='Gerado por')),
            ],
            options={
                'verbose_name': 'Relevé de Carrière',
                'verbose_name_plural': 'Relevés de Carrière',
                'ordering': ['-generated_at'],
            },
        ),
    ]
