# Generated by Django 5.2.15 on 2026-06-18 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("verification", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="verificationlog",
            new_name="verificatio_card_nu_eca2e4_idx",
            old_name="verificatio_card_nu_idx",
        ),
        migrations.RenameIndex(
            model_name="verificationlog",
            new_name="verificatio_verifie_ebbf22_idx",
            old_name="verificatio_verifie_idx",
        ),
        migrations.RenameIndex(
            model_name="verificationlog",
            new_name="verificatio_result_c67d95_idx",
            old_name="verificatio_result_idx",
        ),
    ]
