# Generated by Django 5.2.15 on 2026-06-18 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("verification", "0002_rename_verificatio_card_nu_idx_verificatio_card_nu_eca2e4_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="verificationlog",
            name="card_number",
            field=models.CharField(blank=True, max_length=30, verbose_name="Número do cartão (snapshot)"),
        ),
    ]
