# Generated by Django 5.2.15 on 2026-06-20 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0002_alter_healthcard_card_number"),
        ("verification", "0003_alter_verificationlog_card_number"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProviderMedicalAct",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("reference", models.CharField(blank=True, max_length=30, unique=True, verbose_name="Referência")),
                ("affiliate_name", models.CharField(max_length=200, verbose_name="Nome do titular")),
                ("affiliate_niss", models.CharField(max_length=15, verbose_name="NISS")),
                (
                    "act_type",
                    models.CharField(
                        choices=[
                            ("CONSULTATION", "Consulta"),
                            ("EXAM", "Exame / Diagnóstico"),
                            ("HOSPITALIZATION", "Hospitalização"),
                            ("MEDICATION", "Medicamentos"),
                            ("SURGERY", "Cirurgia"),
                            ("OTHER", "Outro"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de acto",
                    ),
                ),
                ("act_date", models.DateField(verbose_name="Data do acto")),
                (
                    "estimated_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True, verbose_name="Montante estimado (XOF)"
                    ),
                ),
                ("observations", models.TextField(blank=True, verbose_name="Observações")),
                (
                    "status",
                    models.CharField(
                        choices=[("PENDING", "Pendente"), ("VALIDATED", "Validado"), ("REJECTED", "Rejeitado")],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True, verbose_name="Revisto em")),
                ("review_notes", models.TextField(blank=True, verbose_name="Notas de revisão")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Criado em")),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="medical_acts",
                        to="cards.healthcard",
                        verbose_name="Cartão",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="registered_acts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Prestador",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_medical_acts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Revisto por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Acto Médico",
                "verbose_name_plural": "Actos Médicos",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["status", "created_at"], name="verificatio_status_fdd741_idx"),
                    models.Index(fields=["provider", "created_at"], name="verificatio_provide_e3c81d_idx"),
                ],
            },
        ),
    ]
