# Generated by Django 5.2.15 on 2026-06-20 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("verification", "0004_add_provider_medical_act"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="providermedicalact",
            name="validated_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True, verbose_name="Montante validado (XOF)"
            ),
        ),
        migrations.CreateModel(
            name="ProviderProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "clinic_name",
                    models.CharField(blank=True, max_length=200, verbose_name="Nome da clínica / estabelecimento"),
                ),
                ("specialty", models.CharField(blank=True, max_length=100, verbose_name="Especialidade")),
                ("phone", models.CharField(blank=True, max_length=20, verbose_name="Telefone")),
                ("address", models.CharField(blank=True, max_length=300, verbose_name="Endereço")),
                ("license_number", models.CharField(blank=True, max_length=50, verbose_name="Nº de licença")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provider_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilizador",
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil do Prestador",
                "verbose_name_plural": "Perfis dos Prestadores",
            },
        ),
    ]
