# Generated by Django 5.2.15 on 2026-06-18 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "contact_email",
                    models.EmailField(default="suporte@inss.gw", max_length=254, verbose_name="Email de suporte"),
                ),
                (
                    "contact_phone",
                    models.CharField(default="+245 966 000 000", max_length=30, verbose_name="Telefone"),
                ),
                (
                    "contact_address",
                    models.CharField(default="Av. dos Combatentes, Bissau", max_length=200, verbose_name="Endereço"),
                ),
                ("contact_hours", models.CharField(default="Seg–Sex 08h–17h", max_length=100, verbose_name="Horário")),
                (
                    "show_api_docs",
                    models.BooleanField(
                        default=False,
                        help_text="Se activado, mostra Swagger, ReDoc e OpenAPI Schema no footer público.",
                        verbose_name="Mostrar links API docs no footer",
                    ),
                ),
                (
                    "system_status_label",
                    models.CharField(default="Sistema operacional", max_length=50, verbose_name="Estado do sistema"),
                ),
            ],
            options={
                "verbose_name": "Configurações do Site",
                "verbose_name_plural": "Configurações do Site",
            },
        ),
    ]
