# Generated by Django 5.2.15 on 2026-06-18 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="healthcard",
            name="card_number",
            field=models.CharField(blank=True, max_length=30, unique=True, verbose_name="Número do cartão"),
        ),
    ]
