# Generated by Django 5.2.11 on 2026-06-19 23:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('affiliates', '0001_initial'),
        ('employers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=30, unique=True, verbose_name='Referência')),
                ('claim_type', models.CharField(choices=[('CONTRIBUTION_ERROR', 'Erro em Cotização'), ('BENEFIT_DECISION', 'Contestação de Prestação'), ('CARD_ISSUE', 'Problema com Cartão'), ('PENALTY_DISPUTE', 'Contestação de Penalidade'), ('DATA_ERROR', 'Erro de Dados Pessoais'), ('TECHNICAL', 'Problema Técnico'), ('OTHER', 'Outro')], max_length=30, verbose_name='Tipo de Reclamação')),
                ('subject', models.CharField(max_length=300, verbose_name='Assunto')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('priority', models.CharField(choices=[('LOW', 'Baixa'), ('NORMAL', 'Normal'), ('HIGH', 'Alta'), ('URGENT', 'Urgente')], default='NORMAL', max_length=10, verbose_name='Prioridade')),
                ('related_resource_type', models.CharField(blank=True, max_length=50, verbose_name='Tipo de recurso relacionado')),
                ('related_resource_id', models.CharField(blank=True, max_length=50, verbose_name='ID do recurso relacionado')),
                ('status', models.CharField(choices=[('OPEN', 'Aberta'), ('UNDER_REVIEW', 'Em Análise'), ('ADDITIONAL_INFO', 'Info Adicional Solicitada'), ('RESOLVED', 'Resolvida'), ('REJECTED', 'Rejeitada'), ('ESCALATED', 'Escalada')], default='OPEN', max_length=20, verbose_name='Estado')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Submetida em')),
                ('review_started_at', models.DateTimeField(blank=True, null=True, verbose_name='Revisão iniciada em')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resolvida em')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Prazo (SLA)')),
                ('resolution_notes', models.TextField(blank=True, verbose_name='Notas de resolução')),
                ('rejection_reason', models.CharField(blank=True, max_length=300, verbose_name='Motivo de rejeição')),
                ('satisfaction_rating', models.PositiveIntegerField(blank=True, null=True, verbose_name='Avaliação de satisfação (1-5)')),
                ('satisfaction_comment', models.TextField(blank=True, verbose_name='Comentário de satisfação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('affiliate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='affiliates.affiliate', verbose_name='Afiliado')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_claims', to=settings.AUTH_USER_MODEL, verbose_name='Atribuída a')),
                ('employer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='employers.employer', verbose_name='Empregador')),
                ('filed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='filed_claims', to=settings.AUTH_USER_MODEL, verbose_name='Submetida por')),
            ],
            options={
                'verbose_name': 'Reclamação',
                'verbose_name_plural': 'Reclamações',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ClaimDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('file', models.FileField(upload_to='claims/documents/%Y/%m/', verbose_name='Ficheiro')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Carregado em')),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='claims.claim', verbose_name='Reclamação')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Carregado por')),
            ],
            options={
                'verbose_name': 'Documento de Reclamação',
                'verbose_name_plural': 'Documentos de Reclamações',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ClaimMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='Mensagem')),
                ('is_internal', models.BooleanField(default=False, verbose_name='Nota interna (não visível ao cidadão)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='claims.claim', verbose_name='Reclamação')),
            ],
            options={
                'verbose_name': 'Mensagem de Reclamação',
                'verbose_name_plural': 'Mensagens de Reclamações',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClaimStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, max_length=20, verbose_name='Estado anterior')),
                ('new_status', models.CharField(max_length=20, verbose_name='Novo estado')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Alterado em')),
                ('comment', models.TextField(blank=True, verbose_name='Comentário')),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Alterado por')),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='claims.claim', verbose_name='Reclamação')),
            ],
            options={
                'verbose_name': 'Histórico de Estado de Reclamação',
                'verbose_name_plural': 'Histórico de Estados de Reclamações',
                'ordering': ['changed_at'],
            },
        ),
    ]
