# Generated by Django 5.2.15 on 2026-06-20 08:40

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("claims", "0001_initial"),
        ("employers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployerControl",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("reference", models.CharField(blank=True, max_length=30, unique=True, verbose_name="Referência")),
                (
                    "control_type",
                    models.CharField(
                        choices=[
                            ("ROUTINE", "Contrôle de Routine"),
                            ("TARGETED", "Contrôle Ciblé"),
                            ("COMPLAINT", "Déclenché par Réclamation"),
                            ("CROSS_CHECK", "Recoupement Fiscal"),
                        ],
                        default="ROUTINE",
                        max_length=20,
                        verbose_name="Tipo de Controlo",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANNED", "Planificado"),
                            ("IN_PROGRESS", "Em Curso"),
                            ("PV_DRAFTED", "PV Redigido"),
                            ("NOTIFIED", "Notificado"),
                            ("DISPUTED", "Contestado"),
                            ("SETTLED", "Regularizado"),
                            ("CLOSED", "Encerrado"),
                        ],
                        default="PLANNED",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                ("period_from", models.DateField(verbose_name="Período de (início)")),
                ("period_to", models.DateField(verbose_name="Período até (fim)")),
                ("findings_summary", models.TextField(blank=True, verbose_name="Síntese das constatações")),
                ("pv_reference", models.CharField(blank=True, max_length=50, verbose_name="Referência do PV")),
                ("pv_date", models.DateField(blank=True, null=True, verbose_name="Data do PV")),
                ("pv_notes", models.TextField(blank=True, verbose_name="Notas do PV")),
                ("notified_at", models.DateTimeField(blank=True, null=True, verbose_name="Notificado em")),
                (
                    "notification_deadline",
                    models.DateField(blank=True, null=True, verbose_name="Prazo de resposta do empregador"),
                ),
                (
                    "total_assessed",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=15, verbose_name="Total Avaliado"
                    ),
                ),
                (
                    "total_penalties",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=15, verbose_name="Total Penalidades"
                    ),
                ),
                (
                    "total_due",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=15, verbose_name="Total a Pagar"
                    ),
                ),
                (
                    "total_paid",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=15, verbose_name="Total Pago"
                    ),
                ),
                (
                    "total_remaining",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=15, verbose_name="Montante Restante"
                    ),
                ),
                ("dispute_reason", models.TextField(blank=True, verbose_name="Motivo da contestação")),
                (
                    "dispute_filed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Contestação apresentada em"),
                ),
                ("closed_at", models.DateTimeField(blank=True, null=True, verbose_name="Encerrado em")),
                ("closure_notes", models.TextField(blank=True, verbose_name="Notas de encerramento")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Criado em")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Atualizado em")),
                (
                    "assigned_agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assigned_controls",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Agente Responsável",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_controls",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "employer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="controls",
                        to="employers.employer",
                        verbose_name="Empregador",
                    ),
                ),
                (
                    "triggered_by_claim",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="triggered_controls",
                        to="claims.claim",
                        verbose_name="Reclamação que gerou este controlo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Controlo de Empregador",
                "verbose_name_plural": "Controlos de Empregadores",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ControlStatusHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("old_status", models.CharField(blank=True, max_length=20, verbose_name="Estado anterior")),
                ("new_status", models.CharField(max_length=20, verbose_name="Novo estado")),
                ("changed_at", models.DateTimeField(auto_now_add=True, verbose_name="Alterado em")),
                ("comment", models.TextField(blank=True, verbose_name="Comentário")),
                (
                    "changed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Alterado por",
                    ),
                ),
                (
                    "control",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="controls.employercontrol",
                        verbose_name="Controlo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Histórico de Estado de Controlo",
                "verbose_name_plural": "Histórico de Estados de Controlo",
                "ordering": ["changed_at"],
            },
        ),
        migrations.CreateModel(
            name="ControlPayment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12, verbose_name="Montante")),
                ("payment_date", models.DateField(verbose_name="Data de pagamento")),
                (
                    "payment_reference",
                    models.CharField(blank=True, max_length=100, verbose_name="Referência de pagamento"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("PENDING", "Pendente"), ("CONFIRMED", "Confirmado"), ("REJECTED", "Rejeitado")],
                        default="PENDING",
                        max_length=10,
                        verbose_name="Estado",
                    ),
                ),
                ("recorded_at", models.DateTimeField(auto_now_add=True, verbose_name="Registado em")),
                ("notes", models.TextField(blank=True, verbose_name="Notas")),
                (
                    "recorded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Registado por",
                    ),
                ),
                (
                    "control",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="controls.employercontrol",
                        verbose_name="Controlo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pagamento de Redressamento",
                "verbose_name_plural": "Pagamentos de Redressamento",
                "ordering": ["-payment_date"],
            },
        ),
        migrations.CreateModel(
            name="ControlDocument",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("PV", "Procès-Verbal"),
                            ("EMPLOYER_RESPONSE", "Resposta do Empregador"),
                            ("PROOF_PAYMENT", "Comprovativo de Pagamento"),
                            ("SUPPORTING", "Documento de Suporte"),
                            ("OTHER", "Outro"),
                        ],
                        max_length=25,
                        verbose_name="Tipo de documento",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nome")),
                ("file", models.FileField(upload_to="controls/documents/%Y/%m/", verbose_name="Ficheiro")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True, verbose_name="Carregado em")),
                ("notes", models.CharField(blank=True, max_length=300, verbose_name="Notas")),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Carregado por",
                    ),
                ),
                (
                    "control",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="controls.employercontrol",
                        verbose_name="Controlo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento de Controlo",
                "verbose_name_plural": "Documentos de Controlo",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="ControlAssessment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("period_year", models.PositiveIntegerField(verbose_name="Ano")),
                (
                    "period_month",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                        verbose_name="Mês",
                    ),
                ),
                (
                    "declared_salary",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12, verbose_name="Salário Declarado"
                    ),
                ),
                (
                    "actual_salary",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12, verbose_name="Salário Real"
                    ),
                ),
                (
                    "salary_difference",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12, verbose_name="Diferença Salarial"
                    ),
                ),
                (
                    "assessed_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12, verbose_name="Montante Avaliado (12%)"
                    ),
                ),
                (
                    "penalty_rate",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.1000"), max_digits=5, verbose_name="Taxa de penalidade"
                    ),
                ),
                (
                    "penalty_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12, verbose_name="Penalidade"
                    ),
                ),
                (
                    "total_line",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12, verbose_name="Total Linha"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notas")),
                (
                    "control",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessments",
                        to="controls.employercontrol",
                        verbose_name="Controlo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Linha de Redressamento",
                "verbose_name_plural": "Linhas de Redressamento",
                "ordering": ["period_year", "period_month"],
                "unique_together": {("control", "period_year", "period_month")},
            },
        ),
    ]
