# Generated by Django 5.2.15 on 2026-06-18 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="auditevent",
            new_name="audit_audit_action_d7f04a_idx",
            old_name="audit_audit_action_timestamp_idx",
        ),
        migrations.RenameIndex(
            model_name="auditevent",
            new_name="audit_audit_resourc_2ab5ff_idx",
            old_name="audit_audit_resource_type_id_idx",
        ),
        migrations.RenameIndex(
            model_name="auditevent",
            new_name="audit_audit_user_id_314539_idx",
            old_name="audit_audit_user_timestamp_idx",
        ),
    ]
