# Generated by Django 5.2.11 on 2026-06-20 00:57

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('affiliates', '0001_initial'),
        ('contributions', '0002_careerstatementlog'),
        ('employers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollDeclaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=40, unique=True, verbose_name='Referência')),
                ('period_year', models.PositiveIntegerField(verbose_name='Ano do período')),
                ('period_month', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Mês do período')),
                ('status', models.CharField(choices=[('DRAFT', 'Rascunho'), ('SUBMITTED', 'Submetida'), ('VALIDATED', 'Validada'), ('REJECTED', 'Rejeitada')], default='DRAFT', max_length=10, verbose_name='Estado')),
                ('total_employees', models.PositiveIntegerField(default=0, verbose_name='Nº trabalhadores')),
                ('total_salary_base', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total salários')),
                ('total_employee_contributions', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total cotizações trabalhador')),
                ('total_employer_contributions', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total cotizações empregador')),
                ('total_contributions', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total geral')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Submetida em')),
                ('validated_at', models.DateTimeField(blank=True, null=True, verbose_name='Validada em')),
                ('validation_notes', models.TextField(blank=True, verbose_name='Notas de validação')),
                ('rejected_at', models.DateTimeField(blank=True, null=True, verbose_name='Rejeitada em')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Motivo de rejeição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizada em')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_declarations', to=settings.AUTH_USER_MODEL, verbose_name='Criada por')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_declarations', to='employers.employer', verbose_name='Empregador')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_declarations', to=settings.AUTH_USER_MODEL, verbose_name='Rejeitada por')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_declarations', to=settings.AUTH_USER_MODEL, verbose_name='Validada por')),
            ],
            options={
                'verbose_name': 'Declaração de Massa Salarial',
                'verbose_name_plural': 'Declarações de Massa Salarial',
                'ordering': ['-period_year', '-period_month'],
                'unique_together': {('employer', 'period_year', 'period_month')},
            },
        ),
        migrations.CreateModel(
            name='PayrollDeclarationLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_base', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Salário base')),
                ('employee_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0400'), max_digits=5, verbose_name='Taxa trabalhador')),
                ('employer_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0800'), max_digits=5, verbose_name='Taxa empregador')),
                ('employee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Cota trabalhador')),
                ('employer_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Cota empregador')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='Notas')),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='declaration_lines', to='affiliates.affiliate', verbose_name='Afiliado')),
                ('contribution', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='declaration_line', to='contributions.contribution', verbose_name='Contribuição gerada')),
                ('declaration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='payroll.payrolldeclaration', verbose_name='Declaração')),
            ],
            options={
                'verbose_name': 'Linha de Declaração',
                'verbose_name_plural': 'Linhas de Declaração',
                'ordering': ['affiliate__full_name'],
                'unique_together': {('declaration', 'affiliate')},
            },
        ),
    ]
