# Generated by Django 5.2.15 on 2026-06-19 22:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("affiliates", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BenefitType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("RETIREMENT", "Pensão de Reforma"),
                            ("DISABILITY", "Pensão de Invalidez"),
                            ("SURVIVOR", "Pensão de Sobrevivência"),
                            ("FAMILY", "Abono de Família"),
                            ("SICKNESS", "Subsídio de Doença"),
                            ("WORK_ACCIDENT", "Acidente de Trabalho"),
                            ("DEATH", "Subsídio de Morte"),
                        ],
                        max_length=20,
                        verbose_name="Categoria",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nome")),
                ("description", models.TextField(blank=True, verbose_name="Descrição")),
                (
                    "min_contribution_months",
                    models.PositiveIntegerField(default=0, verbose_name="Meses mínimos de contribuição"),
                ),
                (
                    "calculation_method",
                    models.CharField(
                        choices=[
                            ("FIXED", "Montante fixo"),
                            ("PERCENTAGE", "Percentagem do salário"),
                            ("FORMULA", "Fórmula personalizada"),
                        ],
                        default="FIXED",
                        max_length=20,
                        verbose_name="Método de cálculo",
                    ),
                ),
                (
                    "fixed_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True, verbose_name="Montante fixo (XOF)"
                    ),
                ),
                (
                    "percentage_of_salary",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Percentagem do salário (%)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Criado em")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Atualizado em")),
            ],
            options={
                "verbose_name": "Tipo de Prestação",
                "verbose_name_plural": "Tipos de Prestações",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="BenefitRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("reference", models.CharField(blank=True, max_length=30, unique=True, verbose_name="Referência")),
                ("applicant_name", models.CharField(max_length=200, verbose_name="Nome do requerente")),
                ("applicant_niss", models.CharField(max_length=15, verbose_name="NISS do requerente")),
                ("applicant_birth_date", models.DateField(verbose_name="Data de nascimento do requerente")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Rascunho"),
                            ("SUBMITTED", "Submetida"),
                            ("UNDER_REVIEW", "Em revisão"),
                            ("ADDITIONAL_DOCS", "Documentos adicionais"),
                            ("APPROVED", "Aprovada"),
                            ("REJECTED", "Rejeitada"),
                            ("PAYING", "Em pagamento"),
                            ("CLOSED", "Encerrada"),
                        ],
                        default="DRAFT",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                ("justification", models.TextField(verbose_name="Justificação")),
                ("requested_start_date", models.DateField(verbose_name="Data de início pretendida")),
                (
                    "contribution_months_count",
                    models.PositiveIntegerField(default=0, verbose_name="Meses de contribuição"),
                ),
                (
                    "average_salary",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Salário médio"),
                ),
                ("is_eligible", models.BooleanField(blank=True, null=True, verbose_name="Elegível")),
                ("submitted_at", models.DateTimeField(blank=True, null=True, verbose_name="Submetida em")),
                ("review_started_at", models.DateTimeField(blank=True, null=True, verbose_name="Revisão iniciada em")),
                ("decided_at", models.DateTimeField(blank=True, null=True, verbose_name="Decisão em")),
                ("decision_notes", models.TextField(blank=True, verbose_name="Notas de decisão")),
                ("rejection_reason", models.CharField(blank=True, max_length=200, verbose_name="Motivo de rejeição")),
                (
                    "approved_monthly_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True, verbose_name="Montante mensal aprovado"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Criado em")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Atualizado em")),
                (
                    "affiliate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="benefit_requests",
                        to="affiliates.affiliate",
                        verbose_name="Afiliado",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_benefit_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_benefit_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Revisado por",
                    ),
                ),
                (
                    "benefit_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requests",
                        to="benefits.benefittype",
                        verbose_name="Tipo de prestação",
                    ),
                ),
            ],
            options={
                "verbose_name": "Solicitação de Prestação",
                "verbose_name_plural": "Solicitações de Prestações",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BenefitDocument",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("ID_CARD", "Bilhete de Identidade"),
                            ("BIRTH_CERT", "Certidão de Nascimento"),
                            ("MEDICAL_CERT", "Atestado Médico"),
                            ("EMPLOYER_CERT", "Declaração do Empregador"),
                            ("BANK_STATEMENT", "Extrato Bancário"),
                            ("OTHER", "Outro"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de documento",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nome")),
                ("file", models.FileField(upload_to="benefits/documents/%Y/%m/", verbose_name="Ficheiro")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True, verbose_name="Carregado em")),
                ("notes", models.CharField(blank=True, max_length=300, verbose_name="Notas")),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Carregado por",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="benefits.benefitrequest",
                        verbose_name="Solicitação",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento de Prestação",
                "verbose_name_plural": "Documentos de Prestações",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="BenefitStatusHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("old_status", models.CharField(blank=True, max_length=20, verbose_name="Estado anterior")),
                ("new_status", models.CharField(max_length=20, verbose_name="Novo estado")),
                ("changed_at", models.DateTimeField(auto_now_add=True, verbose_name="Alterado em")),
                ("comment", models.TextField(blank=True, verbose_name="Comentário")),
                (
                    "changed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Alterado por",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="benefits.benefitrequest",
                        verbose_name="Solicitação",
                    ),
                ),
            ],
            options={
                "verbose_name": "Histórico de Estado",
                "verbose_name_plural": "Histórico de Estados",
                "ordering": ["-changed_at"],
            },
        ),
        migrations.CreateModel(
            name="BenefitPayment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("period_year", models.PositiveIntegerField(verbose_name="Ano do período")),
                ("period_month", models.PositiveIntegerField(verbose_name="Mês do período")),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12, verbose_name="Montante")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Agendado"),
                            ("PAID", "Pago"),
                            ("FAILED", "Falhou"),
                            ("CANCELLED", "Cancelado"),
                        ],
                        default="SCHEDULED",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                ("scheduled_date", models.DateField(verbose_name="Data agendada")),
                ("paid_date", models.DateField(blank=True, null=True, verbose_name="Data de pagamento")),
                (
                    "payment_reference",
                    models.CharField(blank=True, max_length=100, verbose_name="Referência de pagamento"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notas")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Criado em")),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="benefits.benefitrequest",
                        verbose_name="Solicitação",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pagamento de Prestação",
                "verbose_name_plural": "Pagamentos de Prestações",
                "ordering": ["-period_year", "-period_month"],
                "unique_together": {("request", "period_year", "period_month")},
            },
        ),
    ]
