# Generated by Django 5.2.15 on 2026-06-18 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="notification",
            new_name="notificatio_recipie_86ea8b_idx",
            old_name="notif_recipient_is_read_created_idx",
        ),
    ]
